# Generated by Django 2.1.1 on 2018-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(blank=True, default='', max_length=255)),
                ('street_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=32)),
                ('value', models.CharField(default='', max_length=1024)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('uri', models.CharField(blank=True, default='', max_length=1024)),
                ('id_type', models.CharField(blank=True, choices=[('PATIENT_ID_FHIR', 'Patient ID FHIR'), ('MPI', 'Master Patient Index'), ('SSN', 'Social Security Number'), ('MEDICIAD_ID', 'Medicaid ID Number'), ('MEDICICARE_HICN', 'Medicare HICN (Legacy)'), ('MEDICIARE_ID', 'Medicare ID Number')], default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', max_length=32)),
                ('addresses', models.ManyToManyField(blank=True, to='accounts.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=32)),
                ('value', models.CharField(default='', max_length=1024)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('uri', models.CharField(blank=True, default='', max_length=1024)),
                ('id_type', models.CharField(blank=True, choices=[('FEIN', 'Federal Employer ID Number (Tax ID)'), ('NPI', 'National Provider Identifier'), ('OEID', 'Other Entity Identifier'), ('PECOS', 'PECOS Medicare ID')], default='', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Birthdate', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TMF', 'Transgender Male to Female'), ('TFM', 'Transgender Female to Mmale'), ('U', 'Unknown')], default='U', help_text='Gender / Gender Identity', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', help_text='Sex', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uhi',
            field=models.CharField(blank=True, default='', editable=False, help_text='Universal Health ID', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, default='', help_text='US numbers only.', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.OrganizationIdentifier'),
        ),
        migrations.AddField(
            model_name='address',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.OrganizationIdentifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='accounts.IndividualIdentifier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='accounts.Organization'),
        ),
    ]
