# Generated by Django 2.1.1 on 2018-11-13 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181106_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(on_delete='PROTECT', to=settings.AUTH_USER_MODEL),
        ),
    ]
