# Generated by Django 2.1.1 on 2018-10-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181027_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname or other alias names used.', max_length=255),
        ),
    ]
