# Generated by Django 2.1.1 on 2018-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, default='', editable=False, help_text='Auto-generated subject identifier.', max_length=40),
        ),
    ]
