# Generated by Django 2.1.1 on 2018-10-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181027_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TMF', 'Transgender Male to Female'), ('TFM', 'Transgender Female to Male'), ('U', 'Unknown')], default='U', help_text='Gender / Gender Identity', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname, alias, or other names used.', max_length=255),
        ),
    ]
