# Generated by Django 2.1.1 on 2018-11-15 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_organizationaffiliationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Subject for identity token', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='organizationaffiliationrequest',
            unique_together={('user', 'organization')},
        ),
    ]
