# Generated by Django 2.1.1 on 2018-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181027_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uhi',
            field=models.CharField(blank=True, default='', help_text='Universal Health ID', max_length=15),
        ),
    ]
