# Generated by Django 2.2.4 on 2019-11-23 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191107_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persontopersonrelationship',
            name='grantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persontoperson_grantor', to=settings.AUTH_USER_MODEL),
        ),
    ]
