# Generated by Django 2.2.10 on 2020-03-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200319_1628'),
        ('accounts', '0009_userprofile_verifying_agent_email'),
    ]

    operations = [
    ]
