# Generated by Django 2.1.1 on 2018-12-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181218_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='individualidentifier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizationidentifier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_change_profile_another_user', 'Can change basic profile for another user.'),)},
        ),
    ]
