# Generated by Django 2.2.10 on 2020-06-09 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20200325_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='open_member_enrollment',
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='auto_ial_2_for_agents_description',
            field=models.TextField(blank=True, default='Verified offline. Documents on file.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='These are the members of an organization. (i.e. customers)', related_name='org_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
