# Generated by Django 2.2.10 on 2020-06-09 16:37

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200609_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.TextField(blank=True, default='', help_text='A personal website.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Agents are employees, contractors or persons acting on behalf of the organization.', related_name='org_staff', to=settings.AUTH_USER_MODEL, verbose_name='Organizational Agents'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='United States phone numbers only.', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'Blank'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='', help_text='Specify birth sex, not gender identity.', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verifying_agent_email',
            field=models.EmailField(blank=True, default='', help_text='Email of agent performing identity verification.', max_length=254),
        ),
    ]
