# Generated by Django 2.2.10 on 2020-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_idcardconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardconfirmation',
            name='org_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
