# Generated by Django 2.2.10 on 2020-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_idcardconfirmation_org_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_groups_for_agents',
            field=models.ManyToManyField(blank=True, help_text='All new agents will be added to these groups by default.', to='auth.Group'),
        ),
    ]
