# Generated by Django 2.2.10 on 2020-09-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200929_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
