# Generated by Django 2.2.10 on 2020-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_organization_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='identifiers',
            field=models.ManyToManyField(blank=True, related_name='organization_identifiers', to='accounts.OrganizationIdentifier'),
        ),
    ]
