# Generated by Django 2.2.10 on 2020-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualidentifier',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationidentifier',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationidentifier',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationidentifier',
            name='uri',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='organizationidentifier',
            name='type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
