# Generated by Django 2.1.8 on 2019-07-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190718_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='If populated, restrict email registration to this address.', max_length=512, verbose_name='Email Domain'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_point_of_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='126971563185199', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Employees or contractors acting on behalf of the organization.', related_name='org_staff', to=settings.AUTH_USER_MODEL, verbose_name='Organization Agents'),
        ),
        migrations.AlterField(
            model_name='organizationaffiliationrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationaffiliationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
