# Generated by Django 2.2.10 on 2020-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200929_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationidentifier',
            name='type',
            field=models.CharField(blank=True, choices=[('FEIN', 'Federal Employer ID Number (Tax ID)'), ('NPI', 'National Provider Identifier'), ('OEID', 'Other Entity Identifier'), ('PECOS', 'PECOS Medicare ID'), ('MEDICAID', 'State Provider  /Medicaid ID'), ('NETWORK_ID', 'Insurance/Network ID'), ('DIRECT_DOMAIN', 'Direct Domain'), ('DIRECT_ADDRESS', 'Direct Address'), ('EMAIL', 'Email Address (Additional)'), ('FHIR', 'FHIR Endpoint')], db_index=True, default='', max_length=255),
        ),
    ]
