# Generated by Django 2.1.8 on 2019-07-30 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20190730_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_ial_2_for_agents',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='member',
            field=models.ManyToManyField(blank=True, help_text='This field is a placeholder and is not supported in this version.', related_name='org_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='224749421555238', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Employees or contractors acting on behalf of the organization.', related_name='org_staff', to=settings.AUTH_USER_MODEL, verbose_name='Organization Agent'),
        ),
    ]
