# Generated by Django 2.2.13 on 2020-12-29 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20200929_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persontopersonrelationship',
            old_name='description',
            new_name='relationship_text',
        ),
        migrations.AddField(
            model_name='persontopersonrelationship',
            name='created_by',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='persontopersonrelationship',
            name='relationship_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='persontopersonrelationship',
            name='scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='persontopersonrelationship',
            name='grantee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persontoperson_grantee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UpstreamIdentityProviderToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_idp_sub', models.TextField(db_index=True)),
                ('upstream_idp_vendor', models.TextField(blank=True, default='')),
                ('first_name', models.TextField(blank=True, default='')),
                ('last_name', models.TextField(blank=True, default='')),
                ('email', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UpstreamIdentityProviderToUser_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='persontopersonrelationship',
            name='upstream_idp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UpstreamIdentityProviderToUser'),
        ),
    ]
