# Generated by Django 2.1.8 on 2019-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0021_auto_20190730_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_ial_2_for_agents_description',
            field=models.TextField(blank=True, default='Documents verified by i9 employment'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_groups_for_agents',
            field=models.ManyToManyField(blank=True, help_text='All new agents will be in these groups by default.', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='499461855159754', help_text='Subject ID', max_length=64),
        ),
    ]
