# Generated by Django 2.2.13 on 2020-12-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201229_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persontopersonrelationship',
            name='upstream_idp',
        ),
    ]
