# Generated by Django 2.1.8 on 2019-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190730_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='851492615847752', help_text='Subject ID', max_length=64),
        ),
    ]
