# Generated by Django 2.2.13 on 2021-01-04 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_remove_persontopersonrelationship_upstream_idp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upstreamidentityprovidertouser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='upstreamidentityprovidertouser',
            name='upstream_idp_aud',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='upstreamidentityprovidertouser',
            name='upstream_idp_iss',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='persontopersonrelationship',
            name='relationship_type',
            field=models.TextField(blank=True, choices=[('SELF', 'Self'), ('PARENT-OR-GUARDIAN', 'Parent Guardian of Minor'), ('SPOUSE', 'Spouse'), ('ADULT-DELEGATE', 'Adult Delegate')], default=''),
        ),
        migrations.AlterField(
            model_name='upstreamidentityprovidertouser',
            name='upstream_idp_vendor',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='upstreamidentityprovidertouser',
            unique_together={('upstream_idp_sub', 'upstream_idp_vendor', 'user')},
        ),
        migrations.RemoveField(
            model_name='upstreamidentityprovidertouser',
            name='last_name',
        ),
    ]
