# Generated by Django 2.2.13 on 2021-01-08 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_auto_20210104_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontopersonrelationship',
            name='delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persontoperson_delegate', to=settings.AUTH_USER_MODEL, verbose_name='Delegate'),
        ),
        migrations.AddField(
            model_name='persontopersonrelationship',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persontoperson_subject', to=settings.AUTH_USER_MODEL, verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='persontopersonrelationship',
            unique_together={('delegate', 'subject')},
        ),
        migrations.RemoveField(
            model_name='persontopersonrelationship',
            name='grantee',
        ),
        migrations.RemoveField(
            model_name='persontopersonrelationship',
            name='grantor',
        ),
    ]
