# Generated by Django 2.2.13 on 2021-01-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0025_auto_20210108_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamIdentityProviderUserAuthenticatorAssurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_idp_sub', models.TextField(db_index=True)),
                ('upstream_idp_vendor', models.TextField(blank=True, default='')),
                ('upstream_idp_iss', models.TextField(blank=True, default='')),
                ('upstream_idp_aud', models.TextField(blank=True, default='')),
                ('amr', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
