# Generated by Django 2.2.13 on 2021-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_upstreamidentityprovideruserauthenticatorassurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamidentityprovideruserauthenticatorassurance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='upstreamidentityprovideruserauthenticatorassurance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='upstreamidentityprovidertouser',
            name='upstream_idp_sub',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
