# Generated by Django 2.1.8 on 2019-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190730_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='733471398654738', help_text='Subject ID', max_length=64),
        ),
    ]
