# Generated by Django 2.1.5 on 2019-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20190730_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='562896717259361', help_text='Subject ID', max_length=64),
        ),
    ]
