# Generated by Django 2.2.4 on 2019-08-22 20:43

from django.db import migrations, models


def forward(apps, schema_editor):
    # Set any UserProfile or Organization .picture field with the previous default value to None
    db = schema_editor.connection.alias
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.using(db).filter(picture='profile-picture/None/no-img.jpg').update(
        picture=None)
    Organization = apps.get_model('accounts', 'Organization')
    Organization.objects.using(db).filter(picture='organization-logo/None/no-img.jpg').update(
        picture=None)


def reverse(apps, schema_editor):
    # Set any UserProfile or Organization .picture field with None to the previous default value
    db = schema_editor.connection.alias
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.using(db).filter(picture=None).update(
        picture='profile-picture/None/no-img.jpg')
    Organization = apps.get_model('accounts', 'Organization')
    Organization.objects.using(db).filter(picture=None).update(
        picture='organization-logo/None/no-img.jpg')


class Migration(migrations.Migration):

    dependencies = [('accounts', '0028_auto_20190806_1455')]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='picture',
            field=models.ImageField(upload_to='organization-logo/', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='profile-picture/', null=True),
        ),
        migrations.RunPython(forward, reverse),
    ]
