# Generated by Django 2.2.18 on 2021-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210210_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='subject_qrcodes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject_qrcode_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
