# Generated by Django 2.2.18 on 2021-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210423_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subject_qrcode_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
