# Generated by Django 2.2.4 on 2019-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_account_picture_default_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Middle Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='138382329667494', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(choices=[('', 'Not specified.'), ('male', 'Male'), ('female', 'Female'), ('transgender-male-to-female', 'Transgender Male to Female'), ('trangender-female-to-male', 'Transgender Female to Male'), ('unknown', 'Unknown')], default='U', help_text='Gender / Gender Identity', max_length=3),
        ),
    ]
