# Generated by Django 2.2.4 on 2019-08-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190826_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='964461845246360', help_text='Subject ID', max_length=64),
        ),
    ]
