# Generated by Django 2.2.4 on 2019-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190826_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='223323587857837', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('transgender-male-to-female', 'Transgender Male to Female'), ('trangender-female-to-male', 'Transgender Female to Male'), ('unknown', 'Unknown')], default='', help_text='Gender Identity is not necessarily the same as birth sex.', max_length=64),
        ),
    ]
