# Generated by Django 2.2.4 on 2019-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190903_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='organization-logo/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='872332657691475', help_text='Subject ID', max_length=64),
        ),
    ]
