# Generated by Django 2.2.4 on 2019-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20190905_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password_recovery_phrase',
            new_name='password_recovery_passphrase',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_recovery_passphrase_hash',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='827562995932266', help_text='Subject ID', max_length=64),
        ),
    ]
