# Generated by Django 2.2.4 on 2019-09-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0037_auto_20190905_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='243746381592398', help_text='Subject ID', max_length=64),
        ),
        migrations.CreateModel(
            name='PersonToPersonRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('grantee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persontoperson_grantee', to=settings.AUTH_USER_MODEL)),
                ('grantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persontoperson_grantor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
