# Generated by Django 2.2.4 on 2019-09-05 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0038_auto_20190905_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='972127698434888', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='persontopersonrelationship',
            unique_together={('grantor', 'grantee')},
        ),
    ]
