# Generated by Django 2.2.4 on 2019-09-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20190905_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualidentifier',
            name='uri',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='name',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='type',
            field=models.CharField(blank=True, choices=[('PATIENT_ID_FHIR', 'Patient ID in FHIR'), ('MPI', 'Master Patient Index (Not FHIR Patient ID)'), ('SSN', 'Social Security Number'), ('MEDICAID_ID', 'Medicaid ID Number'), ('MEDICICARE_HICN', 'Medicare HICN (Legacy)'), ('MEDICIARE_ID', 'Medicare ID Number'), ('INDURANCE_ID', 'Insurance ID Number'), ('IHE_ID', 'Health Information Exchange ID'), ('NPI', 'National Provider Identifier'), ('UHI', 'Universal Health Identifier')], db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='934313589386133', help_text='Subject ID', max_length=64),
        ),
    ]
