# Generated by Django 2.2.4 on 2019-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20190917_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='883274242263120', help_text='Subject ID', max_length=64),
        ),
    ]
