# Generated by Django 2.2.4 on 2019-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20190917_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='315768462222227', help_text='Subject ID', max_length=64),
        ),
    ]
