# Generated by Django 2.2.4 on 2019-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20190917_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attest_training_completed',
            field=models.BooleanField(blank=True, default=False, help_text='Yes, I attest that I have completed the training for this system and will abide by the code of conduct.'),
        ),
        migrations.AlterField(
            model_name='individualidentifier',
            name='type',
            field=models.CharField(blank=True, choices=[('PATIENT_ID_FHIR', 'Patient ID in FHIR'), ('MPI', 'Master Patient Index (Not FHIR Patient ID)'), ('SSN', 'Social Security Number'), ('MEDICAID_ID', 'Medicaid ID Number'), ('MEDICARE_HICN', 'Medicare HICN (Legacy)'), ('MEDICARE_ID', 'Medicare ID Number'), ('INSURANCE_ID', 'Insurance ID Number'), ('IHE_ID', 'Health Information Exchange ID'), ('NPI', 'National Provider Identifier'), ('UHI', 'Universal Health Identifier')], db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='122163672534699', help_text='Subject ID', max_length=64),
        ),
    ]
