# Generated by Django 2.2.4 on 2019-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20190919_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='423894727616760', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='attest_training_completed',
            field=models.BooleanField(blank=True, default=False, help_text='Yes, I attest that I have completed the\n                                                        training for this system and will abide by\n                                                        the code of conduct.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('custom', 'Custom')], default='', help_text='Gender Identity is not necessarily the same as birth sex.', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Gender Neutral'), ('', 'Left Blank')], default='', help_text='Specify sex, not gender identity.', max_length=6),
        ),
    ]
