# Generated by Django 2.2.4 on 2019-10-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20191010_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='279675138419885', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Female'), ('female', 'Male'), ('other', 'Gender Neutral'), ('', 'Left Blank')], default='', help_text='Specify sex, not gender identity.', max_length=6),
        ),
    ]
