# Generated by Django 2.2.4 on 2019-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20191010_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender_identity_custom_value',
            field=models.CharField(blank=True, default='', help_text='Enter a custom value for gender_identity.', max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='272396971937597', help_text='Subject ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Gender Neutral'), ('', 'Left Blank')], default='', help_text='Specify sex, not gender identity.', max_length=6),
        ),
    ]
