# Generated by Django 2.2.4 on 2019-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20191010_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='758176497891152', help_text='Subject ID', max_length=64),
        ),
    ]
