# Generated by Django 2.2.4 on 2019-10-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20191010_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='four_digit_suffix',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_str_include',
            field=models.CharField(blank=True, default='', help_text='Choose up to 10 number to be included in your account number.', max_length=10, verbose_name='Pick Your Own ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Subject ID', max_length=64),
        ),
    ]
