# Generated by Django 2.2.4 on 2019-10-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_organization_number_str_include'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number_str_include',
        ),
    ]
