# Generated by Django 2.2.4 on 2019-10-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_userprofile_number_str_include'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='number_str_include',
        ),
    ]
