# Generated by Django 2.2.4 on 2019-10-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_remove_organization_number_str_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='number_str_include',
            field=models.CharField(blank=True, default='', help_text='Choose up to 10 number to be included in your account number.', max_length=10, verbose_name='Pick Your Own ID'),
        ),
    ]
