# Generated by Django 2.2.4 on 2019-10-12 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0057_auto_20191012_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='organization_addresses', to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='agree_privacy_policy',
            field=models.CharField(blank=True, default='', help_text='Do you agree to the privacy policy?', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='agree_tos',
            field=models.CharField(blank=True, default='', help_text='Do you agree to the terms and conditions?', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_ial_2_for_agents',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_ial_2_for_agents_description',
            field=models.TextField(blank=True, default='Documents verified by i9 employment'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_groups_for_agents',
            field=models.ManyToManyField(blank=True, help_text='All new agents will be in these groups by default.', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='A list of domains separated by white space. If populated, restrict email registration to these domains.', max_length=512, verbose_name='Email Domain(s)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='This field is a placeholder and is not supported in this version.', related_name='org_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_str_include',
            field=models.CharField(blank=True, default='', help_text='Choose up to 10 number to be included in your account number.', max_length=10, verbose_name='Pick Your Own ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='organization',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='organization-logo/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_point_of_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subject',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Subject ID', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Employees or contractors acting on behalf of the organization.', related_name='org_staff', to=settings.AUTH_USER_MODEL, verbose_name='Organization Agent'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
