# Generated by Django 2.2.4 on 2019-10-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20191012_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
    ]
