language: python
python:
  - "3.6"

sudo: false

services:
  - docker

env:
  - TOX_ENV=py36
  - TOX_ENV=flake8

matrix:
  fast_finish: true

install:
  - pip install tox

script: tox -e $TOX_ENV

jobs:
  include:
    - stage: build
      script: make build
      if: branch = master AND type = push
    - stage: deploy
      script: make deploy
      if: branch = master AND type = push

stages:
  - test
  - name: build
    if: head_branch = master AND type = push
  - name: deploy
    if: head_branch = master AND type = push

