language: python
python:
  - "3.6"

sudo: false

env:
  - TOX_ENV=py36
  - TOX_ENV=flake8

matrix:
  fast_finish: true

install:
  - pip install tox

script: tox -e $TOX_ENV

jobs:
  include:
    - stage: build
      script: make build
    - stage: deploy
      script: make deploy

stages:
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master

