import logging
# from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse  # HttpResponseRedirect, Http404,
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.decorators import permission_required
# from ..accounts.models import Organization
# from .decorators import group_required
from datetime import datetime
import csv
# from collections import OrderedDict

# Copyright Videntity Systems Inc.

logger = logging.getLogger('verifymyidentity_.%s' % __name__)

__author__ = "Alan Viars"

# @group_required("some-group")


def orgs_and_agents_report(request):
    filename = datetime.now().strftime('%m-%d-%Y_%H:%M:%S') + '.csv'
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename=' + filename
    rows = []
    row = ["animals", "plants"]
    rows.append(row)
    row = ["cat", "apple tree"]
    rows.append(row)
    row = ["dog", "grass"]
    rows.append(row)

    writer = csv.writer(response, delimiter=',')
    for r in rows:
        # filtered_string = "".join(s for s in c if s in string.printable)
        writer.writerows([r])
    msg = "Org and agents report generated by %s %s." % (
        request.user.first_name, request.user.last_name)
    logger.info(msg)
    return response
