import logging
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from ..accounts.models import Organization, UserProfile
from .decorators import group_required
from datetime import datetime
import csv

# Copyright Videntity Systems Inc.

logger = logging.getLogger('verifymyidentity_.%s' % __name__)

__author__ = "Alan Viars"

#


@login_required
@group_required("OrganizationAgentReport")
def orgs_and_agents_report(request):
    filename = datetime.now().strftime('%m-%d-%Y_%H:%M:%S') + '.csv'
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename=' + filename
    rows = []
    row = ["organization", "point_of_contact", "agent_first_name", "agent_last_name",
           "agent_email", "agent_phone_number",  "agent_last_login"]
    rows.append(row)
    row = []
    for org in Organization.objects.all():
        for agent in org.users.all():
            row.append(org.name)
            if org.point_of_contact == agent:
                row.append("Y")
            else:
                row.append("N")
            up = UserProfile.objects.get(user=agent)
            row = row + [agent.first_name, agent.last_name,
                         agent.email, up.mobile_phone_number, agent.last_login]
            rows.append(row)
            row = []

    writer = csv.writer(response, delimiter=',')
    for r in rows:
        # filtered_string = "".join(s for s in c if s in string.printable)
        writer.writerows([r])
    msg = "Org and agents report generated by %s %s." % (
        request.user.first_name, request.user.last_name)
    logger.info(msg)
    return response
