# Generated by Django 2.1.8 on 2019-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0008_auto_20190730_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_subclassification',
            field=models.CharField(blank=True, choices=[('DRIVERS-LICENSE', "Driver's License"), ('MEDICIAD-CARD', 'Mediciad card'), ('MEDICARE-CARD', 'Medicare card'), ('I9', 'I-9 Employee verification')], default='', max_length=250),
        ),
    ]
