# Generated by Django 2.1.5 on 2019-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0009_identityassuranceleveldocumentation_evidence_subclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('', 'No Identity Assurance evidence'), ('ONE-SUPERIOR-OR-STRONG+', 'One Superior or Strong+ pieces of identity evidence'), ('ONE-STRONG-TWO-FAIR', 'One Strong and Two Fair pieces of identity evidence'), ('TWO-STRONG', 'Two Pieces of Strong identity evidence'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person'), ('KBA', 'Knowledged-Based Identity Verification')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_subclassification',
            field=models.CharField(blank=True, choices=[('DRIVERS-LICENSE', "Driver's License"), ('MEDICIAD-CARD', 'Mediciad card'), ('MEDICARE-CARD', 'Medicare card'), ('I9', 'I-9 Employee verification')], default='', max_length=256),
        ),
    ]
