# Generated by Django 2.2.4 on 2019-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0011_auto_20190903_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityassuranceleveldocumentation',
            old_name='type',
            new_name='evidence_type',
        ),
        migrations.RemoveField(
            model_name='identityassuranceleveldocumentation',
            name='identity_proofing_mode',
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='claims',
            field=models.TextField(blank=True, default='', help_text='A whitespace delimited list of claims supported by this evidence.'),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_date_of_date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_date_of_issuance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_issuer_country',
            field=models.CharField(blank=True, default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_issuer_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_issuer_region',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_number',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('idcard', 'ID Card'), ('passport', 'Passport'), ('driving_permit', 'Driving Permit'), ('us_health_insurance_card', 'US Health and Insurance Card')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_documentation_verification_method_type',
            field=models.CharField(blank=True, choices=[('pipp', 'Physical In-Person Proofing'), ('sripp', 'Supervised remote In-Person Proofing'), ('eid', 'Online verification of an electronic ID card'), ('', 'Blank')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='utility_bill_provider_country',
            field=models.CharField(blank=True, default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='utility_bill_provider_locality',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='utility_bill_provider_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='utility_bill_provider_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='utility_bill_provider_region',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='utility_bill_provider_street_address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
