# Generated by Django 2.2.4 on 2019-10-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0012_auto_20191010_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_issuer_number',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('id_document', 'Verification based on any kind of government issued identity document'), ('utility_bill', 'Verification based on a utility bill'), ('qes', 'Verification based on a eIDAS Qualified Electronic Signature')], default='', max_length=64),
        ),
    ]
