# Generated by Django 2.2.4 on 2019-10-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0013_auto_20191010_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityassuranceleveldocumentation',
            old_name='id_document_date_of_date_of_expiry',
            new_name='id_document_issuer_date_of_issuance',
        ),
        migrations.RenameField(
            model_name='identityassuranceleveldocumentation',
            old_name='id_document_date_of_issuance',
            new_name='id_document_issuer_of_date_of_expiry',
        ),
        migrations.RemoveField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_number',
        ),
    ]
