# Generated by Django 2.2.4 on 2019-10-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0014_auto_20191010_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityassuranceleveldocumentation',
            old_name='id_document_issuer_of_date_of_expiry',
            new_name='id_document_issuer_date_of_expiry',
        ),
    ]
