# Generated by Django 2.2.4 on 2019-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0015_auto_20191010_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('', 'No Identity Assurance evidence'), ('ONE-SUPERIOR-OR-STRONG+', 'One Superior or Strong+ pieces of identity evidence'), ('ONE-STRONG-TWO-FAIR', 'One Strong and Two Fair pieces of identity evidence'), ('TWO-STRONG', 'Two Pieces of Strong identity evidence'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person'), ('KBA', 'Knowledged-Based Identity Verification')], default='', max_length=256, verbose_name='Identity Assurance Classification'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('id_document', 'Verification based on any kind of government issued identity document'), ('utility_bill', 'Verification based on a utility bill')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD.\n                                              If left blank the Identity assurance level of 2\n                                              will not expire.', null=True, verbose_name='Invalidate Identity Assurance Date'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_issuer_date_of_expiry',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True),
        ),
    ]
