# Generated by Django 2.2.4 on 2019-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0016_auto_20191024_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='action',
            field=models.CharField(blank=True, choices=[('', 'Create a record with an IAL of 1 (Default)'), ('1-TO-2', 'Verify Identity: Change the Identity assurance Level from 1 to 2'), ('2-TO-1', 'Administrative Downgrade of this identity Assurance documentation. IAL 2 --> 1 for this piece of evidence'), ('UPDATE', 'Update details only.')], default='', max_length=6),
        ),
    ]
