# Generated by Django 2.2.4 on 2019-10-30 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0018_auto_20191030_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='verifying_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifying_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
