# Generated by Django 2.2.4 on 2019-11-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0019_auto_20191030_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='back_of_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='front_of_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='pdf417_barcode',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='identityassuranceleveldocumentation',
            name='pdf417_barcode_parsed',
            field=models.TextField(blank=True, default='', help_text='The extracted parsed text content from the pdf417_barcode.'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('id_document', 'Verification based on any kind of government issued identity document')], default='id_document', max_length=64),
        ),
    ]
