# Generated by Django 2.2.8 on 2020-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0020_auto_20191123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('ONE-SUPERIOR-OR-STRONG-PLUS', 'One Superior or Strong+ pieces of identity evidence'), ('ONE-STRONG-TWO-FAIR', 'One Strong and Two Fair pieces of identity evidence'), ('TWO-STRONG', 'Two Pieces of Strong identity evidence'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person'), ('KBA', 'Knowledged-Based Identity Verification'), ('', 'No Identity Assurance Evidence')], default='', max_length=256, verbose_name='Identity Assurance Classification'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='expires_at',
            field=models.DateField(blank=True, help_text='If left blank, the Identity Assurance Level\n                                              of 2 will remain in effect indefinitely.', null=True, verbose_name='Invalidate Identity Assurance Date'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_issuer_date_of_expiry',
            field=models.DateField(blank=True, help_text='The date the ID document expires.', null=True),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='note',
            field=models.TextField(blank=True, help_text='Add any notes or secondary card information here.', null=True),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='pdf417_barcode',
            field=models.ImageField(blank=True, null=True, upload_to='identity_documents/', verbose_name="Image of the barcode on the back of the driver's license."),
        ),
    ]
