# Generated by Django 2.2.8 on 2020-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0021_auto_20200107_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityassuranceleveldocumentation',
            name='action',
        ),
        migrations.RemoveField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_subclassification',
        ),
        migrations.RemoveField(
            model_name='identityassuranceleveldocumentation',
            name='id_assurance_downgrade_description',
        ),
        migrations.RemoveField(
            model_name='identityassuranceleveldocumentation',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('ONE-SUPERIOR-OR-STRONG-PLUS', 'One Superior or Strong+ pieces of identity evidence'), ('ONE-STRONG-TWO-FAIR', 'One Strong and Two Fair pieces of identity evidence'), ('TWO-STRONG', 'Two Pieces of Strong identity evidence'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person'), ('KBA', 'Knowledged-Based Identity Verification'), ('ONE-SUPERIOR-OR-STRONG-PLUS-1', "State issued Driver's License or ID Card"), ('ONE-SUPERIOR-OR-STRONG-PLUS-2', 'Passport'), ('ONE-SUPERIOR-OR-STRONG-PLUS-3', 'Veteran ID Card'), ('TWO-STRONG-1', 'At least two of the following documents: birth certificate, Social Security Card, Medicaid card, Medicare Card.'), ('', 'No Identity Assurance Evidence')], default='', max_length=256, verbose_name='Identity Assurance Level 2 Classification'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('id_document', 'Verification based on any kind of government issued identity document'), ('utility_bill', 'Verification based on a utility bill')], default='id_document', max_length=64),
        ),
    ]
