# Generated by Django 2.2.8 on 2020-01-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0022_auto_20200107_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('ONE-SUPERIOR-OR-STRONG-PLUS', 'One Superior or Strong+ pieces of identity evidence'), ('ONE-STRONG-TWO-FAIR', 'One Strong and Two Fair pieces of identity evidence'), ('TWO-STRONG', 'Two Pieces of Strong identity evidence'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person'), ('KBA', 'Knowledged-Based Identity Verification'), ('ONE-SUPERIOR-OR-STRONG-PLUS-1', "Driver's License"), ('ONE-SUPERIOR-OR-STRONG-PLUS-2', 'Identification Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-3', 'Veteran ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-4', 'Passport'), ('TWO-STRONG-1', 'At least two of the following documents: birth certificate,\n                        Social Security Card, Medicaid card, Medicare Card.'), ('', 'No Identity Assurance Evidence')], default='', max_length=256, verbose_name='Identity Assurance Level 2 Classification'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('driving_permit', 'Driving Permit'), ('idcard', 'ID Card'), ('passport', 'Passport'), ('us_health_insurance_card', 'US Health and Insurance Card')], default='', max_length=128),
        ),
    ]
