# Generated by Django 2.2.8 on 2020-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0023_auto_20200107_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person'), ('ONE-SUPERIOR-OR-STRONG-PLUS-1', "Driver's License"), ('ONE-SUPERIOR-OR-STRONG-PLUS-2', 'Identification Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-3', 'Veteran ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-4', 'Passport'), ('ONE-SUPERIOR-OR-STRONG-PLUS-5', 'NY Medicaid ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-6', 'Medicare ID'), ('TWO-STRONG-1', 'Original Birth Certificate and a Social Security Card')], default='', max_length=256, verbose_name='Identity Assurance Level 2 Classification'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('driving_permit', 'Driving License'), ('idcard', 'ID Card'), ('passport', 'Passport'), ('us_health_insurance_card', 'US Health and Insurance Card')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='id_documentation_verification_method_type',
            field=models.CharField(blank=True, choices=[('pipp', 'Physical In-Person Proofing'), ('', 'Blank')], default='', max_length=16),
        ),
    ]
