# Generated by Django 2.2.10 on 2020-06-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0024_auto_20200221_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('ONE-SUPERIOR-OR-STRONG-PLUS-1', "Driver's License"), ('ONE-SUPERIOR-OR-STRONG-PLUS-2', 'Identification Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-3', 'Veteran ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-4', 'Passport'), ('ONE-SUPERIOR-OR-STRONG-PLUS-5', 'NY Medicaid ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-6', 'Medicare ID'), ('TWO-STRONG-1', 'Original Birth Certificate and a Social Security Card'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person')], default='', max_length=256, verbose_name='Identity Assurance Level 2 Classification'),
        ),
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='id_documentation_verification_method_type',
            field=models.CharField(blank=True, choices=[('pipp', 'Physical In-Person Proofing'), ('sripp', 'Supervised Remote In-Person Proofing'), ('eid', 'Online verification of an electronic ID card')], default='pipp', max_length=16),
        ),
    ]
