# Generated by Django 2.2.10 on 2020-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0025_auto_20200609_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('ONE-SUPERIOR-OR-STRONG-PLUS-1', "Driver's License"), ('ONE-SUPERIOR-OR-STRONG-PLUS-2', 'Identification Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-3', 'Veteran ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-4', 'Passport'), ('ONE-SUPERIOR-OR-STRONG-PLUS-5', 'RealID'), ('TWO-STRONG-1', 'Original Birth Certificate and a Social Security Card'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person')], default='', max_length=256, verbose_name='Identity Assurance Level 2 Classification'),
        ),
    ]
