# Generated by Django 2.2.13 on 2021-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ial', '0026_auto_20200908_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityassuranceleveldocumentation',
            name='evidence',
            field=models.CharField(blank=True, choices=[('IAL2-GENERIC', 'Identity Assurance Level 2 (Generic)'), ('IAL2-ON-FILE', 'Identity Assurance Level 2 is on file and/or managed by business rules.)'), ('ONE-SUPERIOR-OR-STRONG-PLUS', 'One Superior or one Strong+ piece of identity evidence'), ('ONE-STRONG-TWO-FAIR', 'One Strong and Two Fair pieces of identity evidence'), ('TWO-STRONG', 'Two Pieces of Strong identity evidence'), ('ONE-SUPERIOR-OR-STRONG-PLUS-1', "Driver's License"), ('ONE-SUPERIOR-OR-STRONG-PLUS-2', 'Identification Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-3', 'Veteran ID Card'), ('ONE-SUPERIOR-OR-STRONG-PLUS-4', 'Passport'), ('ONE-SUPERIOR-OR-STRONG-PLUS-5', 'RealID'), ('TWO-STRONG-1', 'Original Birth Certificate and a Social Security Card'), ('TRUSTED-REFEREE-VOUCH', 'I am a Trusted Referee Vouching for this person')], default='', max_length=256, verbose_name='Identity Assurance Level 2 Classification'),
        ),
    ]
