version: '3'

services:
  db:
    image: postgres
    environment:
            - POSTGRES_DB=vmi
            - POSTGRES_PASSWORD=toor
    ports:
            - "5432:5432"
  web:
    build:
            context: ../
            dockerfile: .development/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
            - DATABASES_CUSTOM=postgres://postgres:toor@db:5432/vmi
            - OAUTHLIB_INSECURE_TRANSPORT=true
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
