# Generated by Django 2.2.18 on 2021-04-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210210_1938'),
        ('healthcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarthealthcard',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AddField(
            model_name='smarthealthcard',
            name='shc_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='shc_qr_codes'),
        ),
        migrations.AddField(
            model_name='smarthealthjwks',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='smarthealthcard',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
