# Generated by Django 2.2.18 on 2021-04-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcards', '0002_auto_20210413_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smarthealthcard',
            old_name='shc_qr_code',
            new_name='shc_qrcode',
        ),
    ]
