# Generated by Django 2.2.18 on 2021-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcards', '0003_auto_20210413_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarthealthjwks',
            name='kid',
            field=models.CharField(blank=True, default='', editable=False, help_text='The KEy ID for the public/private keys. This is often an FQDN.', max_length=255),
        ),
    ]
