# Generated by Django 2.2.18 on 2021-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcards', '0005_remove_smarthealthcard_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarthealthjwks',
            name='kid',
            field=models.CharField(blank=True, default='', editable=False, help_text='The Key ID for the public/private keys. This is often an FQDN.', max_length=255),
        ),
    ]
